' EventModeling-PlantUML
' Version 6.0 - Standard Syntax Styles

' ##################################
' ##          STYLING             ##
' ##################################

skinparam defaultTextAlignment center
skinparam wrapWidth 200
skinparam shadowing false
skinparam roundcorner 5
skinparam defaultFontName "Segoe UI", "Helvetica", "Arial"
skinparam defaultFontSize 14

' ADD THIS: Hides the automatic green 'C' icon
skinparam classStereotypeIcon false

' Style for the slice containers
skinparam package {
  BorderColor #AAAAAA
  BorderStyle solid
  FontColor #555555
  StereotypeFontSize 0
  TitleAlignment left
}

<style>
spot{
  spotClass {
    BackgroundColor: LightGrey;
    FontColor: Black;
    LineColor: Black;
  }
}
</style>

' === Pre-defined colors ===
!$EM_COMMAND_BG = "#BDE0FE"
!$EM_COMMAND_BORDER = "#4361EE"
!$EM_EVENT_BG = "#FFE2B8"
!$EM_EVENT_BORDER = "#FC9E4F"
!$EM_READMODEL_BG = "#D9ED92"
!$EM_READMODEL_BORDER = "#76C893"
!$EM_SYSTEM_BG = "#EAEAEA"
!$EM_SYSTEM_BORDER = "#BDBDBD"
!$EM_POLICY_BG = "#E0BBEA"
!$EM_POLICY_BORDER = "#957DAD"
!$EM_TRIGGER_BG = "#FFFFFF"
!$EM_TRIGGER_BORDER = "#666666"
!$EM_AUTOMATION_BG = "#FFFFFF"
!$EM_AUTOMATION_BORDER = "#666666"


' === All elements are styled using 'class' or 'agent' ===
skinparam class<<Command>> {
  BackgroundColor $EM_COMMAND_BG
  BorderColor $EM_COMMAND_BORDER
}
skinparam class<<Event>> {
  BackgroundColor $EM_EVENT_BG
  BorderColor $EM_EVENT_BORDER
}
skinparam class<<"Read Model">> {
  BackgroundColor $EM_READMODEL_BG
  BorderColor $EM_READMODEL_BORDER
}
skinparam class<<"External System">> {
  BackgroundColor $EM_SYSTEM_BG
  BorderColor $EM_SYSTEM_BORDER
}
skinparam agent<<Policy>> {
  BackgroundColor $EM_POLICY_BG
  BorderColor $EM_POLICY_BORDER
}
skinparam actor {
  BackgroundColor #FFFFFF
  BorderColor #666666
}
skinparam class<<Trigger>> {
  BackgroundColor $EM_TRIGGER_BG
  BorderColor $EM_TRIGGER_BORDER
}
skinparam class<<Automation>> {
  BackgroundColor $EM_AUTOMATION_BG
  BorderColor $EM_AUTOMATION_BORDER
}
