@startuml Test

!include styling.puml

skinparam packageStyle rectangle

package Slice_1 {
  class "Eksternt System" <<(E), External System>> {
    event_id : UUID
  }
}

package Slice_2 {
  "Eksternt System" -down-> Handling2 : publiser/abonnér
  class Handling2 <<Command>> {
    name
    person_id : UUID
  }
  class Hændelse2 <<(E), Event>>{
    event_id : UUID
  }
}

package Slice_3 {
  Hændelse2 -down-> Handling3 : publiser/abonnér
  Handling2 -right-> Hændelse2 : udløser hændelsen
  
  class Handling3 <<Command>> {
    name
    person_id : UUID
  }
  Handling3 -right-> Hændelse3 : udløser hændelsen
  
  class Hændelse3 <<(E), Event>>{
    event_id : UUID
  }
}

@enduml
